[project]
name = "charity-matching-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.charity-matching-token]
path = "contracts/charity-matching-token.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
